### PR TITLE
Add LICENSE file to MANIFEST.in

### PR DESCRIPTION
**Pull request by jenzopr**
Dear Krzysztof,

I'm about to bring `bbknn` into bioconda to allow installation via `conda install bbknn`. 
For a proper conda package, the LICENSE file has to be distributed together with the source code. This PR adds the missing LICENSE file to the MANIFEST.in so that it is included in the packaged source code.

If you're in favor of this PR, please merge and re-upload to Pypi. Please feel free to ask if you have questions.

Best,
Jens

### CODE REVIEW

**Comment by ktpolanski** [comment]
Thanks for this. Sure, can do. Question - is annoy also on conda? Think that's the main dependency that causes setup issues.

EDIT: One google later the answer is yes. So it should be overall a good quality of life thing all around.

**Comment by jenzopr** [comment]
Thank you, Krzysztof!

Yes, annoy is available as `python-annoy` in conda-forge. The recipe for `bbknn` builds successfully, just the linting of the recipe fails due to the missing `LICENSE` file in the source tar.gz file from pypi. This PR includes the file in the source tar.gz. I'm happy to push the recipe to bioconda, once this PR is merged in 👍

**Comment by ktpolanski** [comment]
So you don't actually need me to push this to pip immediately? Or does the success of the operation also depend on this being  in pip, like you mentioned earlier?

**Comment by jenzopr** [comment]
Sorry for my inconsistency - a push to pypi is required for the recipe to build successfully. However, I don't want to pressure you if you have other work you'd like to add. Just let me know once you've created a new version on pypi.

**Comment by ktpolanski** [comment]
Up as 1.3.3 on pip. Thanks again!

**Comment by jenzopr** [comment]
Great! Thank you 🎉  PR is open [here](https://github.com/bioconda/bioconda-recipes/pull/15623) and checks are successful. I guess it will be merged soon :-)

**Pull request merged**
