### PR TITLE
Enable Faiss with GPU support.

### PR DESCRIPTION
**Pull request by canergen**
PR enables GPU support in Faiss, which gives a speed-up of 4x in my hands-on shape (105322, 50). Sklearn fix is most likely a version issue and can be reverted if this is fine on your side.

### CODE REVIEW

**Comment by ktpolanski** [comment]
Seeing how I never dabbled with GPU faiss, I presume the premise is you install `faiss-gpu` rather than `faiss-cpu` from conda and that's it?

Yeah, please revert the sklearn, it was its own thing: https://github.com/Teichlab/bbknn/issues/54

**Comment by canergen** [comment]
Yes, it's just installing faiss-gpu. It's important in my hand to install it with conda and not PyPi to keep track of cudatoolkit. If it's installed wrong (faiss-gpu but not correct cudatoolkit version), copying to GPU takes forever (https://github.com/kyamagu/faiss-wheels/issues/54).

**Comment by ktpolanski** [comment]
Good thing that the readme recommends getting faiss from conda then.

Thanks for the PR!

**Comment by CoolMLAI** [comment]
@canergen, 
thanks a lot. 
I appreciate your help.

**Pull request merged**
